spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waitme8888/spring-cloud
          search-paths: spring-cloud-dalston/demo1-config/config-repo
#          username:
#          password:
#        health:
#          repositories:
server:
  port: 10010